### ISSUE TITLE
g6pd and gstt1  missing from stargazer/1kgp/hg38/?

### ISSUE THREAD

**Issue by brettva** [sbslee/stargazer#1]
Hi Steven, getting errors:

FileNotFoundError: [Errno 2] No such file or directory: stargazer-1.1.5-py3.7.egg/stargazer/1kgp/hg38/g6pd.vcf.gz'
FileNotFoundError: [Errno 2] No such file or directory:stargazer-1.1.5-py3.7.egg/stargazer/1kgp/hg38/gstt1.vcf.gz'

when running:

`stargazer chip hg38 gstt1 {in_vcf} {out_path}`
`stargazer chip hg38 g6pd {in_vcf} {out_path}`
`

It looks like these might be missing from `stargazer/1kgp/hg38` with the distribution?

**Comment by sbslee** [comment]
Hi, Stargazer has been extended to support hg38 data for all of Stargazer’s usual target genes except for those two (G6PD and GSTT1). The G6PD gene is on the X chromosome and the 1000 Genomes Project (1KGP) hasn’t released hg38 reference panel for sex chromosomes yet. Similarly, the GSTT1 gene was also omitted because in hg38 the gene is actually on the alternative contig and 1KGP hasn’t released hg38 reference panel yet for alternative contigs either. We will add those two genes as soon as reference panels become available for those genes.
